project:
  type: website
  output-dir: ./docs

website:
  title: "Pedro Gasparine Dubiela"
  search: false

  # Header
  navbar:
    background: "#1a3d4a"
    foreground: "white"
    pinned: true
    right: 
      - icon: github
        href: https://github.com/pedroDubiela95
      - icon: linkedin 
        href: https://www.linkedin.com/in/pedro-gasparine-dubiela-478430147/ 
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projetos"
        file: projects.qmd

  # Foot
  page-footer:
    background: "#1a3d4a"
    foreground: "white"
    center: "Copyright 2024" 
    border: true

  # Barra
  sidebar:
  - title: "Projetos"
    style: "docked"
    border: true
    background: "#1a3d4a"
    foreground: "white"
    contents:
      - projects.qmd
      - project1.qmd
      - project2.qmd
      - project3.qmd
      
  - title: "fix side"
    contents:
      - fix.qmd
      
format:
  html:
    html-math-method: katex
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    #echo: false



